name: CI-Workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v6
      - name: Print index.html file
        run: cat index.html
