name: CI-Workflow
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo "building the project"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "running test cases"
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: deploy
      run: echo "deploying the app"
